import { ThemeProvider } from "@mui/material";
import { theme } from "./theme/theme";

import ReduxProvider from "./Redux-Provider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
  header,
  footer,
}: {
  children: React.ReactNode;
  header: React.ReactNode;
  footer: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ margin: 0 }}>
        <ThemeProvider theme={theme}>
          {header}
          <ReduxProvider>{children}</ReduxProvider>
          {footer}
        </ThemeProvider>
      </body>
    </html>
  );
}
