import { ThemeProvider } from "@mui/material";
import { theme } from "./theme/theme";
import { ClerkProvider } from "@clerk/nextjs";
import CssBaseline from "@mui/material/CssBaseline";
import Header from "./_components/Header";
import ReduxProvider from "./redux-provider";

import "./globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
  footer,
}: {
  children: React.ReactNode;
  footer: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body style={{ margin: 0 }}>
          <ThemeProvider theme={theme}>
            <ReduxProvider>
              <CssBaseline />
              <Header />
              {children}
            </ReduxProvider>
            {footer}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
